version: "3"
services:
  o11pro:
    hostname: "o11pro"
    container_name: "o11pro"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "O11_PORT=6123"
      - "O11_EPG_PORT=6125"
      - "ADMIN_USER=admin"
      - "ADMIN_PASSWORD=admin"
    image: "ghcr.io/cyb3rgh05t/docker-o11pro:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    ports:
      - "6123:6123"
      - "6125:6125"
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/o11pro:/opt/o11"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
